apiVersion: v1
kind: Pod
metadata:
  name: pod-with-http
spec:
  containers:
    - name: web
      image: hashicorp/http-echo
      args:
        - "-text=Hello from Web Container"
        - "-listen=:8080"
      ports:
        - containerPort: 8080

    - name: client
      image: busybox
      command: ["sh", "-c"]
      args:
        - |
          while true; do \
            echo ">>> $(date): pinging http://localhost:8080" && \
            curl -qO- http://localhost:8080; \
            sleep 5; \
          done
