apiVersion: v1
kind: Pod
metadata:
  name: pod-with-http
spec:
  containers:
    - name: web
      image: hashicorp/http-echo
      args:
        - "-text=Hello from Web Container"
        - "-listen=:8080"
      ports:
        - containerPort: 8080

    - name: client
      image: busybox
      command: ["sh", "-c"]
      args:
        - |
          for i in $(seq 1 10); do \
            echo ">>> Attempt $i to connect to localhost:8080..." && \
            wget -qO- http://localhost:8080 && break || sleep 1; \
          done && \
          sleep 3600
